# Generated by Django 2.2.7 on 2019-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crconnectprocess_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crconnectprocess',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='crconnectprocess',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crconnectprocess',
            name='text',
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='department_chair_signature',
            field=models.FileField(default='', help_text='Signed PDF provided by Docusign', upload_to='', verbose_name='Department Chair Signature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='pi_computing_id',
            field=models.EmailField(default='', max_length=254, verbose_name="Principal Investigator's computing ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='pi_experience_description',
            field=models.TextField(default='', verbose_name="Describe the PI's experience"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='responsible_organization',
            field=models.CharField(default='', max_length=1000, verbose_name='Responsible Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='study_abstract',
            field=models.TextField(default='', max_length=1000, verbose_name='Study Abstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='study_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Study Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='study_title',
            field=models.CharField(default='', max_length=1000, verbose_name='Study Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='study_type',
            field=models.CharField(choices=[('full_board', 'Full Board'), ('expedited', 'Expedited'), ('non_engaged', 'Non-Engaged'), ('exempt', 'Exempt'), ('non_human', 'Non-Human'), ('emergency_use', 'Emergency Use')], default='', max_length=1000, verbose_name='Study Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crconnectprocess',
            name='will_have_contract',
            field=models.BooleanField(default=False, verbose_name='Study will have a contract'),
            preserve_default=False,
        ),
    ]
