"""empty message

Revision ID: 0accb57bf013
Revises: e9092efd6f26
Create Date: 2020-01-23 10:52:49.343854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0accb57bf013'
down_revision = 'e9092efd6f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_spec', sa.Column('primary_process_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_spec', 'primary_process_id')
    # ### end Alembic commands ###
