"""empty message

Revision ID: 0c8a2f8db28c
Revises: 8856126b6658
Create Date: 2020-03-13 14:05:46.983484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a2f8db28c'
down_revision = '8856126b6658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('is_reference', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'is_reference')
    # ### end Alembic commands ###
