"""empty message

Revision ID: 1fb36d682c7f
Revises: e8cc6a9245f3
Create Date: 2022-01-12 12:28:48.577819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb36d682c7f'
down_revision = 'e8cc6a9245f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_log', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_log', 'timestamp')
    # ### end Alembic commands ###
