"""empty message

Revision ID: 2a6f7ea00e5f
Revises: dc30b8f6571c
Create Date: 2021-07-29 10:51:56.857341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6f7ea00e5f'
down_revision = 'dc30b8f6571c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('library_spec_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['library_spec_id'], ['workflow_spec.id'], ),
    sa.ForeignKeyConstraint(['workflow_spec_id'], ['workflow_spec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workflow_spec', sa.Column('library', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_spec', 'library')
    op.drop_table('workflow_library')
    # ### end Alembic commands ###
