"""empty message

Revision ID: 2c88e49d0ffc
Revises: 726d09a4fa0c
Create Date: 2020-02-27 11:17:01.768161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c88e49d0ffc'
down_revision = '726d09a4fa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('inactive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'inactive')
    # ### end Alembic commands ###
