"""empty message

Revision ID: 301c4fd103d2
Revises: 0ae9742a2b14
Create Date: 2020-03-05 15:36:06.750422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301c4fd103d2'
down_revision = '0ae9742a2b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('spec_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'spec_version')
    # ### end Alembic commands ###
