"""empty message

Revision ID: 369d65dcb269
Revises: c4ddb69e7ef4
Create Date: 2020-07-27 20:05:29.524553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369d65dcb269'
down_revision = 'c4ddb69e7ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('changes_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'changes_history')
    # ### end Alembic commands ###
