"""empty message

Revision ID: 3876e130664e
Revises: 5064b72284b7
Create Date: 2020-06-01 15:39:53.937591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3876e130664e'
down_revision = '5064b72284b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_event', sa.Column('task_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_event', 'task_data')
    # ### end Alembic commands ###
