"""empty message

Revision ID: 3c56c894ff5c
Revises: 29bad12c9945
Create Date: 2022-02-17 11:52:52.335700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c56c894ff5c'
down_revision = '29bad12c9945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_file', sa.Column('file_timestamp', sa.FLOAT(), nullable=True))
    op.drop_column('lookup_file', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_file', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lookup_file', 'file_timestamp')
    # ### end Alembic commands ###
