"""empty message

Revision ID: 476f8a4933ba
Revises: 7be7cecbeea8
Create Date: 2020-04-17 12:10:38.962672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476f8a4933ba'
down_revision = '7be7cecbeea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('primary_process_id', sa.String(), nullable=True))
    op.drop_column('workflow_spec', 'primary_process_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_spec', sa.Column('primary_process_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file', 'primary_process_id')
    # ### end Alembic commands ###
