"""empty message

Revision ID: 4d9ae1a4eb48
Revises: 2b787cc265d8
Create Date: 2020-03-19 17:13:40.747794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9ae1a4eb48'
down_revision = '2b787cc265d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('irb_doc_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'irb_doc_code')
    # ### end Alembic commands ###
