"""empty message

Revision ID: 5e0709e172fa
Revises: ddd5fc9ea75b
Create Date: 2020-03-26 14:05:06.607043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0709e172fa'
down_revision = 'ddd5fc9ea75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_spec_category', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_spec_category', 'display_order')
    # ### end Alembic commands ###
