"""empty message

Revision ID: 62910318009f
Revises: 665624ac29f1
Create Date: 2021-04-28 14:09:57.648732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62910318009f'
down_revision = '665624ac29f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_data', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_data', 'size')
    # ### end Alembic commands ###
