"""empty message

Revision ID: 62a11a335778
Revises: 17597692d0b0
Create Date: 2020-06-09 22:45:52.475183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a11a335778'
down_revision = '17597692d0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_html', sa.String(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
