"""empty message

Revision ID: 6c98925e62cf
Revises: 0accb57bf013
Create Date: 2020-02-03 20:45:26.692679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c98925e62cf'
down_revision = '0accb57bf013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('study_id', sa.String(), nullable=True))
    op.add_column('file', sa.Column('task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'file', 'workflow_spec', ['study_id'], ['id'])
    op.create_foreign_key(None, 'file', 'workflow_spec', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'task_id')
    op.drop_column('file', 'study_id')
    # ### end Alembic commands ###
