"""empty message

Revision ID: 726d09a4fa0c
Revises: 0a6e0b829398
Create Date: 2020-02-26 16:35:05.854328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726d09a4fa0c'
down_revision = '0a6e0b829398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('investigator_uids', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('study', sa.Column('user_uid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'study', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'user_uid')
    op.drop_column('study', 'investigator_uids')
    # ### end Alembic commands ###
