"""empty message

Revision ID: 7be7cecbeea8
Revises: 7c0de7621a1f
Create Date: 2020-04-09 14:23:37.384927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be7cecbeea8'
down_revision = '7c0de7621a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_spec', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_spec', 'display_order')
    # ### end Alembic commands ###
