"""empty message

Revision ID: 7ec759f994c8
Revises: cb892916166a
Create Date: 2021-03-01 12:51:53.681624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '7ec759f994c8'
down_revision = 'cb892916166a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from lookup_data')
    op.execute('delete from lookup_file')
    op.add_column('lookup_file', sa.Column('task_spec_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lookup_file', 'task_spec_id')
    # ### end Alembic commands ###
