"""empty message

Revision ID: 839f6f255b81
Revises: 17597692d0b0
Create Date: 2020-06-17 16:22:05.076206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839f6f255b81'
down_revision = '17597692d0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_html', sa.String(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
