"""empty message

Revision ID: 8f0d445dd297
Revises: 28752ce0775c
Create Date: 2022-03-17 16:51:29.873798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0d445dd297'
down_revision = '28752ce0775c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'progress')
    # ### end Alembic commands ###
