"""empty message

Revision ID: 923031daaa09
Revises: 5c63a89ee7b7
Create Date: 2021-10-05 15:37:40.846299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923031daaa09'
down_revision = '5c63a89ee7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'primary_investigator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('primary_investigator_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
