"""empty message

Revision ID: a931e2b7b070
Revises: 47b10b171d7c
Create Date: 2021-07-12 08:46:08.814577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a931e2b7b070'
down_revision = 'c16d3047abbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('library_spec_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['library_spec_id'], ['workflow_spec.id'], ),
    sa.ForeignKeyConstraint(['workflow_spec_id'], ['workflow_spec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_library')
    # ### end Alembic commands ###
