"""empty message

Revision ID: b08b710163e2
Revises: 
Create Date: 2023-01-11 10:39:28.022336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b08b710163e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('admin_impersonate_uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('ldap_model',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('telephone_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('sponsor_type', sa.String(), nullable=True),
    sa.Column('date_cached', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('lookup_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('task_spec_id', sa.String(), nullable=True),
    sa.Column('field_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_timestamp', sa.FLOAT(), nullable=True),
    sa.Column('is_ldap', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lookup_file_model_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lookup_file_model_id'], ['lookup_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['ldap_model.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'hold', 'open_for_enrollment', 'abandoned', 'cr_connect_complete', name='studystatus'), nullable=True),
    sa.Column('irb_status', sa.Enum('incomplete_in_protocol_builder', 'completed_in_protocol_builder', name='irbstatus'), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_type', sa.Integer(), nullable=True),
    sa.Column('primary_investigator', sa.String(), nullable=True),
    sa.Column('progress_status', sa.Enum('in_progress', 'submitted_for_pre_review', 'in_pre_review', 'returned_from_pre_review', 'pre_review_complete', 'agenda_date_set', 'approved', 'approved_with_conditions', 'deferred', 'disapproved', 'ready_for_pre_review', 'resubmitted_for_pre_review', 'finance_in_progress', name='progressstatus'), nullable=True),
    sa.Column('sponsor', sa.String(), nullable=True),
    sa.Column('ind_number', sa.String(), nullable=True),
    sa.Column('investigator_uids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('requirements', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('on_hold', sa.Boolean(), nullable=True),
    sa.Column('proposal_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=True),
    sa.Column('cc', sa.String(), nullable=True),
    sa.Column('bcc', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_html', sa.String(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_associated_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['ldap_model.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'hold', 'open_for_enrollment', 'abandoned', 'cr_connect_complete', name='studystatus'), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('user', 'automatic', name='studyeventtype'), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpmn_workflow_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'user_input_required', 'waiting', 'complete', 'erroring', name='workflowstatus'), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('state_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_doc_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('doc_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('task_spec', sa.String(), nullable=True),
    sa.Column('irb_doc_code', sa.String(), nullable=False),
    sa.Column('md5_hash', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('spec_version', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('task_title', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('task_state', sa.String(), nullable=True),
    sa.Column('task_lane', sa.String(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('mi_type', sa.String(), nullable=True),
    sa.Column('mi_count', sa.Integer(), nullable=True),
    sa.Column('mi_index', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('workflow_spec_id', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('task_spec', sa.String(), nullable=True),
    sa.Column('spec_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_store')
    op.drop_table('task_log')
    op.drop_table('task_event')
    op.drop_table('file')
    op.drop_table('email_doc_codes')
    op.drop_table('workflow')
    op.drop_table('study_event')
    op.drop_table('study_associated_user')
    op.drop_table('email')
    op.drop_table('study')
    op.drop_table('user')
    op.drop_table('lookup_data')
    op.drop_table('lookup_file')
    op.drop_table('ldap_model')
    op.drop_table('admin_session')
    # ### end Alembic commands ###
