"""empty message

Revision ID: b0f38c78db40
Revises: a931e2b7b070
Create Date: 2021-07-14 09:30:42.562825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f38c78db40'
down_revision = 'a931e2b7b070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_spec', sa.Column('library', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_spec', 'library')
    # ### end Alembic commands ###
