"""empty message

Revision ID: c4ddb69e7ef4
Revises: ffef4661a37d
Create Date: 2020-07-22 09:04:09.769239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ddb69e7ef4'
down_revision = 'ffef4661a37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'enrollment_date')
    # ### end Alembic commands ###
