"""empty message

Revision ID: c6261ac7a7bc
Revises: f186725c1ad3
Create Date: 2021-02-10 08:01:45.451881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6261ac7a7bc'
down_revision = 'f186725c1ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('is_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'is_review')
    # ### end Alembic commands ###
