"""empty message

Revision ID: c872232ebdcb
Revises: f28ee3722c49
Create Date: 2021-03-02 14:35:13.911050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c872232ebdcb'
down_revision = 'f28ee3722c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from lookup_data')
    op.execute('delete from lookup_file')
    op.add_column('lookup_file', sa.Column('task_spec_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lookup_file', 'task_spec_id')
    # ### end Alembic commands ###