"""empty message

Revision ID: d08b0fffc43e
Revises: f9c4e92a8afe
Create Date: 2020-02-05 14:53:25.664026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08b0fffc43e'
down_revision = 'f9c4e92a8afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('form_field_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'form_field_key')
    # ### end Alembic commands ###
