"""add columns

Revision ID: e0dfdbfd6f69
Revises: 0718ad13e5f3
Create Date: 2020-11-09 08:33:04.585139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dfdbfd6f69'
down_revision = '0718ad13e5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_store', sa.Column('spec_id', sa.String(), nullable=True))
    op.add_column('data_store', sa.Column('study_id', sa.Integer(), nullable=True))
    op.add_column('data_store', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('data_store', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('data_store', sa.Column('workflow_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_store', 'workflow_id')
    op.drop_column('data_store', 'user_id')
    op.drop_column('data_store', 'task_id')
    op.drop_column('data_store', 'study_id')
    op.drop_column('data_store', 'spec_id')
    # ### end Alembic commands ###
