"""empty message

Revision ID: efdc41cc7fbf
Revises: 44dd9397c555
Create Date: 2022-01-07 10:51:43.400986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdc41cc7fbf'
down_revision = '44dd9397c555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_log', sa.Column('user_uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_log', 'user_uid')
    # ### end Alembic commands ###
