"""empty message

Revision ID: f186725c1ad3
Revises: e0dfdbfd6f69
Create Date: 2020-11-13 11:01:31.882424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f186725c1ad3'
down_revision = 'e0dfdbfd6f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_store', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_store', 'last_updated')
    # ### end Alembic commands ###
