"""empty message

Revision ID: f527568787e5
Revises: 28752ce0775c
Create Date: 2022-03-17 20:07:03.864323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f527568787e5'
down_revision = '28752ce0775c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('review_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'review_type')
    # ### end Alembic commands ###
