"""empty message

Revision ID: f93185c45e75
Revises: 28752ce0775c
Create Date: 2022-03-18 10:20:05.815435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93185c45e75'
down_revision = '28752ce0775c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('primary_investigator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'primary_investigator')
    # ### end Alembic commands ###
