openapi: "3.0.2"
info:
  version: 1.0.0
  title: Workflow Microservice
  license:
    name: MIT
servers:
  - url: http://localhost:5000/v1.0
security:
  - jwt: ['secret']
paths:
  /login:
    get:
      # operationId: crc.api.user.login_v2
      operationId: crc.shared.test_blueprint.show
      summary: In production, logs the user in via SSO. If not in production, logs in as a specific user for testing.
      security: []  # Disable security for this endpoint only.
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            type: string
        - name: redirect_url
          in: query
          required: false
          schema:
            type: string
      tags:
        - Users
      responses:
        '304':
          description: Redirection to the hosted frontend with an auth_token header.
